require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - .git/**/*
    - node_modules/**/*
    - vendor/**/*
    - bin/**/*


# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 200

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - '*'
  Max: 100

RSpec/MultipleExpectations:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Max: 8
